import { Room, Student, Payment, AdminUser, DormSettings } from "./types";
import { MASTER_ADMIN } from "./constants";

export const defaultSettings: DormSettings = {
  dormName: "Turar joy",
  defaultPrice: 500000,
  dueDay: 10,
  currency: "UZS",
};

export const seedRooms: Record<string, Room> = {
  "room-1": {
    id: "room-1",
    number: "101",
    floor: 1,
    building: "A",
    capacity: 1,
    type: "single",
    pricePerMonth: 500000,
    status: "occupied",
    amenities: ["WiFi", "Konditsioner"],
    currentOccupants: 1,
  },
  "room-2": {
    id: "room-2",
    number: "102",
    floor: 1,
    building: "A",
    capacity: 2,
    type: "double",
    pricePerMonth: 750000,
    status: "occupied",
    amenities: ["WiFi", "Konditsioner", "Idish-osh jihozlari"],
    currentOccupants: 2,
  },
  "room-3": {
    id: "room-3",
    number: "103",
    floor: 1,
    building: "A",
    capacity: 3,
    type: "triple",
    pricePerMonth: 1000000,
    status: "occupied",
    amenities: ["WiFi", "Konditsioner", "Idish-osh jihozlari", "TV"],
    currentOccupants: 2,
  },
  "room-4": {
    id: "room-4",
    number: "201",
    floor: 2,
    building: "A",
    capacity: 1,
    type: "single",
    pricePerMonth: 500000,
    status: "available",
    amenities: ["WiFi", "Konditsioner"],
    currentOccupants: 0,
  },
  "room-5": {
    id: "room-5",
    number: "202",
    floor: 2,
    building: "A",
    capacity: 2,
    type: "double",
    pricePerMonth: 750000,
    status: "occupied",
    amenities: ["WiFi", "Konditsioner", "Idish-osh jihozlari"],
    currentOccupants: 1,
  },
  "room-6": {
    id: "room-6",
    number: "301",
    floor: 3,
    building: "A",
    capacity: 1,
    type: "single",
    pricePerMonth: 550000,
    status: "maintenance",
    amenities: ["WiFi"],
    currentOccupants: 0,
  },
  "room-7": {
    id: "room-7",
    number: "101",
    floor: 1,
    building: "B",
    capacity: 2,
    type: "double",
    pricePerMonth: 700000,
    status: "occupied",
    amenities: ["WiFi", "Konditsioner"],
    currentOccupants: 2,
  },
  "room-8": {
    id: "room-8",
    number: "102",
    floor: 1,
    building: "B",
    capacity: 3,
    type: "triple",
    pricePerMonth: 950000,
    status: "occupied",
    amenities: ["WiFi", "Konditsioner", "Idish-osh jihozlari"],
    currentOccupants: 3,
  },
  "room-9": {
    id: "room-9",
    number: "201",
    floor: 2,
    building: "B",
    capacity: 1,
    type: "single",
    pricePerMonth: 480000,
    status: "occupied",
    amenities: ["WiFi", "Konditsioner"],
    currentOccupants: 1,
  },
  "room-10": {
    id: "room-10",
    number: "202",
    floor: 2,
    building: "B",
    capacity: 2,
    type: "double",
    pricePerMonth: 720000,
    status: "available",
    amenities: ["WiFi", "Konditsioner"],
    currentOccupants: 0,
  },
  "room-11": {
    id: "room-11",
    number: "101",
    floor: 1,
    building: "C",
    capacity: 1,
    type: "single",
    pricePerMonth: 450000,
    status: "occupied",
    amenities: ["WiFi"],
    currentOccupants: 1,
  },
  "room-12": {
    id: "room-12",
    number: "102",
    floor: 1,
    building: "C",
    capacity: 2,
    type: "double",
    pricePerMonth: 680000,
    status: "available",
    amenities: ["WiFi", "Konditsioner"],
    currentOccupants: 0,
  },
  "room-13": {
    id: "room-13",
    number: "201",
    floor: 2,
    building: "C",
    capacity: 3,
    type: "triple",
    pricePerMonth: 900000,
    status: "occupied",
    amenities: ["WiFi", "Konditsioner", "Idish-osh jihozlari"],
    currentOccupants: 2,
  },
  "room-14": {
    id: "room-14",
    number: "202",
    floor: 2,
    building: "C",
    capacity: 1,
    type: "single",
    pricePerMonth: 460000,
    status: "occupied",
    amenities: ["WiFi"],
    currentOccupants: 1,
  },
  "room-15": {
    id: "room-15",
    number: "301",
    floor: 3,
    building: "C",
    capacity: 2,
    type: "double",
    pricePerMonth: 700000,
    status: "available",
    amenities: ["WiFi", "Konditsioner"],
    currentOccupants: 0,
  },
};

export const seedStudents: Record<string, Student> = {
  "student-1": {
    id: "student-1",
    fullName: "Abdullayev Ali",
    studentId: "STU001",
    faculty: "Informatika",
    year: 1,
    phone: "+998901234567",
    email: "ali.abdullayev@edu.uz",
    roomId: "room-1",
    checkInDate: "2025-09-01",
    checkOutDate: null,
    status: "active",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=ali",
  },
  "student-2": {
    id: "student-2",
    fullName: "Qo'ldoshova Nasiba",
    studentId: "STU002",
    faculty: "Kimyo",
    year: 2,
    phone: "+998902345678",
    email: "nasiba.qoldoshova@edu.uz",
    roomId: "room-2",
    checkInDate: "2025-09-01",
    checkOutDate: null,
    status: "active",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=nasiba",
  },
  "student-3": {
    id: "student-3",
    fullName: "Karimov Javohir",
    studentId: "STU003",
    faculty: "Informatika",
    year: 3,
    phone: "+998903456789",
    email: "javohir.karimov@edu.uz",
    roomId: "room-2",
    checkInDate: "2024-09-01",
    checkOutDate: null,
    status: "active",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=javohir",
  },
  "student-4": {
    id: "student-4",
    fullName: "Usmanova Gulnar",
    studentId: "STU004",
    faculty: "Fizika",
    year: 1,
    phone: "+998904567890",
    email: "gulnar.usmanova@edu.uz",
    roomId: "room-3",
    checkInDate: "2025-09-01",
    checkOutDate: null,
    status: "active",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=gulnar",
  },
  "student-5": {
    id: "student-5",
    fullName: "Miroyev Mirza",
    studentId: "STU005",
    faculty: "Matematika",
    year: 2,
    phone: "+998905678901",
    email: "mirza.miroyev@edu.uz",
    roomId: "room-3",
    checkInDate: "2025-09-01",
    checkOutDate: null,
    status: "active",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=mirza",
  },
  "student-6": {
    id: "student-6",
    fullName: "Tashmatova Dilfuza",
    studentId: "STU006",
    faculty: "Biologiya",
    year: 1,
    phone: "+998906789012",
    email: "dilfuza.tashmatova@edu.uz",
    roomId: "room-5",
    checkInDate: "2025-09-01",
    checkOutDate: null,
    status: "active",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=dilfuza",
  },
  "student-7": {
    id: "student-7",
    fullName: "Nazarov Sardor",
    studentId: "STU007",
    faculty: "Iqtisodiyot",
    year: 3,
    phone: "+998907890123",
    email: "sardor.nazarov@edu.uz",
    roomId: "room-7",
    checkInDate: "2024-09-01",
    checkOutDate: null,
    status: "active",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=sardor",
  },
  "student-8": {
    id: "student-8",
    fullName: "Kadieva Zarina",
    studentId: "STU008",
    faculty: "Xorijiy tillar",
    year: 2,
    phone: "+998908901234",
    email: "zarina.kadieva@edu.uz",
    roomId: "room-7",
    checkInDate: "2025-09-01",
    checkOutDate: null,
    status: "active",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=zarina",
  },
  "student-9": {
    id: "student-9",
    fullName: "Rahmonov Rustam",
    studentId: "STU009",
    faculty: "Informatika",
    year: 4,
    phone: "+998909012345",
    email: "rustam.rahmonov@edu.uz",
    roomId: "room-8",
    checkInDate: "2023-09-01",
    checkOutDate: null,
    status: "active",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=rustam",
  },
  "student-10": {
    id: "student-10",
    fullName: "Ismatova Noila",
    studentId: "STU010",
    faculty: "Kimyo",
    year: 1,
    phone: "+998910123456",
    email: "noila.ismatova@edu.uz",
    roomId: "room-8",
    checkInDate: "2025-09-01",
    checkOutDate: null,
    status: "active",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=noila",
  },
  "student-11": {
    id: "student-11",
    fullName: "Shodmonov Shodlik",
    studentId: "STU011",
    faculty: "Fizika",
    year: 2,
    phone: "+998911234567",
    email: "shodlik.shodmonov@edu.uz",
    roomId: "room-9",
    checkInDate: "2025-09-01",
    checkOutDate: null,
    status: "active",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=shodlik",
  },
  "student-12": {
    id: "student-12",
    fullName: "Mamurjonova Dilnoza",
    studentId: "STU012",
    faculty: "Matematika",
    year: 3,
    phone: "+998912345678",
    email: "dilnoza.mamurjonova@edu.uz",
    roomId: "room-11",
    checkInDate: "2024-09-01",
    checkOutDate: null,
    status: "active",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=dilnoza",
  },
  "student-13": {
    id: "student-13",
    fullName: "Xusayinov Khurshed",
    studentId: "STU013",
    faculty: "Biologiya",
    year: 2,
    phone: "+998913456789",
    email: "khurshed.xusayinov@edu.uz",
    roomId: "room-13",
    checkInDate: "2025-09-01",
    checkOutDate: null,
    status: "active",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=khurshed",
  },
  "student-14": {
    id: "student-14",
    fullName: "Anorova Anora",
    studentId: "STU014",
    faculty: "Informatika",
    year: 1,
    phone: "+998914567890",
    email: "anora.anorova@edu.uz",
    roomId: "room-13",
    checkInDate: "2025-09-01",
    checkOutDate: null,
    status: "active",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=anora",
  },
  "student-15": {
    id: "student-15",
    fullName: "Raxmatov Rahmatjon",
    studentId: "STU015",
    faculty: "Xorijiy tillar",
    year: 4,
    phone: "+998915678901",
    email: "rahmatjon.raxmatov@edu.uz",
    roomId: "room-14",
    checkInDate: "2022-09-01",
    checkOutDate: null,
    status: "active",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=rahmatjon",
  },
  "student-16": {
    id: "student-16",
    fullName: "Qosimova Ekaterina",
    studentId: "STU016",
    faculty: "Boshkaruv",
    year: 3,
    phone: "+998916789012",
    email: "ekaterina.qosimova@edu.uz",
    roomId: null,
    checkInDate: null,
    checkOutDate: null,
    status: "active",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=ekaterina",
  },
  "student-17": {
    id: "student-17",
    fullName: "Maxmudov Maxmud",
    studentId: "STU017",
    faculty: "Iqtisodiyot",
    year: 2,
    phone: "+998917890123",
    email: "maxmud.maxmudov@edu.uz",
    roomId: null,
    checkInDate: null,
    checkOutDate: null,
    status: "active",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=maxmud",
  },
  "student-18": {
    id: "student-18",
    fullName: "Samanova Samira",
    studentId: "STU018",
    faculty: "Kimyo",
    year: 1,
    phone: "+998918901234",
    email: "samira.samanova@edu.uz",
    roomId: null,
    checkInDate: null,
    checkOutDate: null,
    status: "active",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=samira",
  },
  "student-19": {
    id: "student-19",
    fullName: "To'raev To'ra",
    studentId: "STU019",
    faculty: "Fizika",
    year: 3,
    phone: "+998919012345",
    email: "tora.toraev@edu.uz",
    roomId: null,
    checkInDate: null,
    checkOutDate: null,
    status: "inactive",
    photoUrl: "https://api.dicebear.com/7.x/avataaars/svg?seed=tora",
  },
};

export const seedPayments: Record<string, Payment> = {
  "payment-1": {
    id: "payment-1",
    studentId: "student-1",
    roomId: "room-1",
    amount: 500000,
    month: "2026-02",
    dueDate: "2026-02-10",
    paidDate: "2026-02-08",
    status: "paid",
    method: "cash",
    notes: "",
  },
  "payment-2": {
    id: "payment-2",
    studentId: "student-1",
    roomId: "room-1",
    amount: 500000,
    month: "2026-03",
    dueDate: "2026-03-10",
    paidDate: "2026-03-12",
    status: "paid",
    method: "transfer",
    notes: "",
  },
  "payment-3": {
    id: "payment-3",
    studentId: "student-1",
    roomId: "room-1",
    amount: 500000,
    month: "2026-04",
    dueDate: "2026-04-10",
    paidDate: null,
    status: "overdue",
    method: null,
    notes: "",
  },
  "payment-4": {
    id: "payment-4",
    studentId: "student-2",
    roomId: "room-2",
    amount: 750000,
    month: "2026-02",
    dueDate: "2026-02-10",
    paidDate: "2026-02-09",
    status: "paid",
    method: "card",
    notes: "",
  },
  "payment-5": {
    id: "payment-5",
    studentId: "student-2",
    roomId: "room-2",
    amount: 750000,
    month: "2026-03",
    dueDate: "2026-03-10",
    paidDate: null,
    status: "unpaid",
    method: null,
    notes: "",
  },
  "payment-6": {
    id: "payment-6",
    studentId: "student-2",
    roomId: "room-2",
    amount: 750000,
    month: "2026-04",
    dueDate: "2026-04-10",
    paidDate: null,
    status: "unpaid",
    method: null,
    notes: "",
  },
  "payment-7": {
    id: "payment-7",
    studentId: "student-3",
    roomId: "room-2",
    amount: 750000,
    month: "2026-02",
    dueDate: "2026-02-10",
    paidDate: "2026-02-07",
    status: "paid",
    method: "cash",
    notes: "",
  },
  "payment-8": {
    id: "payment-8",
    studentId: "student-3",
    roomId: "room-2",
    amount: 750000,
    month: "2026-03",
    dueDate: "2026-03-10",
    paidDate: "2026-03-10",
    status: "paid",
    method: "transfer",
    notes: "",
  },
  "payment-9": {
    id: "payment-9",
    studentId: "student-3",
    roomId: "room-2",
    amount: 750000,
    month: "2026-04",
    dueDate: "2026-04-10",
    paidDate: null,
    status: "unpaid",
    method: null,
    notes: "",
  },
  "payment-10": {
    id: "payment-10",
    studentId: "student-4",
    roomId: "room-3",
    amount: 1000000,
    month: "2026-02",
    dueDate: "2026-02-10",
    paidDate: "2026-02-11",
    status: "paid",
    method: "card",
    notes: "",
  },
};

export const seedAdmins: Record<string, AdminUser> = {
  "admin-master": {
    id: "admin-master",
    username: MASTER_ADMIN.username,
    password: MASTER_ADMIN.password,
    fullName: MASTER_ADMIN.fullName,
    createdAt: "2025-01-01",
  },
};
